Fix crash reported on Google Play
Log:

```
ava.lang.RuntimeException: Unable to resume activity {com.nononsenseapps.notepad/com.nononsenseapps.notepad.ActivityMain_}: java.lang.IllegalArgumentException: account must not be null
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.IllegalArgumentException: account must not be null
at android.content.ContentResolver.isSyncActive(ContentResolver.java:2195)
at com.nononsenseapps.helpers.SyncStatusMonitor.startMonitoring(SyncStatusMonitor.java:44)
at com.nononsenseapps.notepad.ActivityMain.onResume(ActivityMain.java:487)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
at android.app.Activity.performResume(Activity.java:6019)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
... 11 more
```

Signed-off-by: Jonas Kalderstam <jonas@kalderstam.se>